# Generated by Django 4.0.6 on 2022-07-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('question', 'Question'), ('other', 'Other')], max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('body', models.TextField()),
            ],
        ),
    ]
